Fix Upgrade script
Unable to upgrade from FormaLMS 3.3.22 to 3.3.24 as the MySQL error is thrown:

```
Fatal error: Uncaught mysqli_sql_exception: You can't specify target table 'learning_coursereport' for update in FROM clause in /home/robertinho/public_html/ava.example.com/db/drivers/docebodb.mysqli.php:127 Stack trace: #0 /home/robertinho/public_html/ava.example.com/db/drivers/docebodb.mysqli.php(127): mysqli_query(Object(mysqli), 'DELETE FROM lea...') #1 /home/robertinho/public_html/ava.example.com/db/lib.docebodb.php(522): mysqli_DbConn->query('DELETE FROM lea...') #2 /home/robertinho/public_html/ava.example.com/lib/installer/lib.php(111): sql_query('DELETE FROM lea...') #3 /home/robertinho/public_html/ava.example.com/upgrade/upg_data.php(86): importSqlFile('/home/robertinh...', Array) #4 {main} thrown in /home/robertinho/public_html/ava.example.com/db/drivers/docebodb.mysqli.php on line 127
```